language: node_js

os:
    - linux
node_js:
    - 7
    - 6
    - 4

env:
    - NPM=npm@2
    - NPM=npm@4

script:
    - npm install -g $NPM
    - npm install -g yarn
    - npm test

after_success:
    - bash <(curl -s https://codecov.io/bash)
