language: node_js

os:
    - linux
node_js:
    - 16
    - 14
    - 12

script:
    - npm install
    - npm install -g yarn
    - npm test

after_success:
    - bash <(curl -s https://codecov.io/bash)
