language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"

install:
  - npm install

script:
  - npm test

after_success:
  - npm install -g istanbul
  - npm install coveralls
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
