environment:
    matrix:
        - nodejs_version: 8
        - nodejs_version: 6
        # Node 4 doesn't work because of an AppVeyor bug
        # - nodejs_version: 4

install:
    - ps: Install-Product node $env:nodejs_version
    - npm install

test_script:
    - npm install -g yarn
    - node --version
    - npm --version
    - npm test

build: off
