environment:
    - nodejs_version: 7
    - nodejs_version: 6
    - nodejs_version: 4
    - NPM=npm@2
    - NPM=npm@4

install:
    - ps: Install-Product node $env:nodejs_version
    - npm install

test_script:
    - cmd: npm install -g %NPM%
    - npm install -g yarn
    - node --version
    - npm --version
    - npm test

build: off
