environment:
    matrix:
        - nodejs_version: 14
        - nodejs_version: 12

platform:
    - x86

install:
    - ps: Install-Product node $env:nodejs_version
    - npm install

test_script:
    - npm install -g yarn
    - node --version
    - npm --version
    - npm test

build: off
